/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermOfUseRouteImport } from './routes/term-of-use'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MySubjectsRouteImport } from './routes/my-subjects'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as MySubjectsIndexRouteImport } from './routes/my-subjects/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects/$subjectId'
import { Route as MySubjectsTranscriptRouteImport } from './routes/my-subjects/transcript'
import { Route as MySubjectsProgressRouteImport } from './routes/my-subjects/progress'
import { Route as MySubjectsPlanRouteImport } from './routes/my-subjects/plan'
import { Route as MySubjectsGradesRouteImport } from './routes/my-subjects/grades'
import { Route as AdminProgramsRouteImport } from './routes/admin/programs'
import { Route as AdminFacultiesRouteImport } from './routes/admin/faculties'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminCurriculaRouteImport } from './routes/admin/curricula'
import { Route as AdminCurriculumGroupCurriculumIdRouteImport } from './routes/admin/curriculum-group/$curriculumId'

const TermOfUseRoute = TermOfUseRouteImport.update({
  id: '/term-of-use',
  path: '/term-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MySubjectsRoute = MySubjectsRouteImport.update({
  id: '/my-subjects',
  path: '/my-subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const MySubjectsIndexRoute = MySubjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MySubjectsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const MySubjectsTranscriptRoute = MySubjectsTranscriptRouteImport.update({
  id: '/transcript',
  path: '/transcript',
  getParentRoute: () => MySubjectsRoute,
} as any)
const MySubjectsProgressRoute = MySubjectsProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => MySubjectsRoute,
} as any)
const MySubjectsPlanRoute = MySubjectsPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => MySubjectsRoute,
} as any)
const MySubjectsGradesRoute = MySubjectsGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => MySubjectsRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/admin/programs',
  path: '/admin/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/admin/faculties',
  path: '/admin/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurriculaRoute = AdminCurriculaRouteImport.update({
  id: '/admin/curricula',
  path: '/admin/curricula',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurriculumGroupCurriculumIdRoute =
  AdminCurriculumGroupCurriculumIdRouteImport.update({
    id: '/admin/curriculum-group/$curriculumId',
    path: '/admin/curriculum-group/$curriculumId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-subjects': typeof MySubjectsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/term-of-use': typeof TermOfUseRoute
  '/admin/curricula': typeof AdminCurriculaRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/my-subjects/grades': typeof MySubjectsGradesRoute
  '/my-subjects/plan': typeof MySubjectsPlanRoute
  '/my-subjects/progress': typeof MySubjectsProgressRoute
  '/my-subjects/transcript': typeof MySubjectsTranscriptRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/my-subjects/': typeof MySubjectsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/admin/curriculum-group/$curriculumId': typeof AdminCurriculumGroupCurriculumIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/term-of-use': typeof TermOfUseRoute
  '/admin/curricula': typeof AdminCurriculaRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/my-subjects/grades': typeof MySubjectsGradesRoute
  '/my-subjects/plan': typeof MySubjectsPlanRoute
  '/my-subjects/progress': typeof MySubjectsProgressRoute
  '/my-subjects/transcript': typeof MySubjectsTranscriptRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/admin': typeof AdminIndexRoute
  '/my-subjects': typeof MySubjectsIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/admin/curriculum-group/$curriculumId': typeof AdminCurriculumGroupCurriculumIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-subjects': typeof MySubjectsRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/term-of-use': typeof TermOfUseRoute
  '/admin/curricula': typeof AdminCurriculaRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/my-subjects/grades': typeof MySubjectsGradesRoute
  '/my-subjects/plan': typeof MySubjectsPlanRoute
  '/my-subjects/progress': typeof MySubjectsProgressRoute
  '/my-subjects/transcript': typeof MySubjectsTranscriptRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/my-subjects/': typeof MySubjectsIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/admin/curriculum-group/$curriculumId': typeof AdminCurriculumGroupCurriculumIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/my-subjects'
    | '/privacy-policy'
    | '/profile'
    | '/reviews'
    | '/sign-in'
    | '/sign-up'
    | '/term-of-use'
    | '/admin/curricula'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/programs'
    | '/my-subjects/grades'
    | '/my-subjects/plan'
    | '/my-subjects/progress'
    | '/my-subjects/transcript'
    | '/subjects/$subjectId'
    | '/admin/'
    | '/my-subjects/'
    | '/subjects/'
    | '/admin/curriculum-group/$curriculumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy-policy'
    | '/profile'
    | '/reviews'
    | '/sign-in'
    | '/sign-up'
    | '/term-of-use'
    | '/admin/curricula'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/programs'
    | '/my-subjects/grades'
    | '/my-subjects/plan'
    | '/my-subjects/progress'
    | '/my-subjects/transcript'
    | '/subjects/$subjectId'
    | '/admin'
    | '/my-subjects'
    | '/subjects'
    | '/admin/curriculum-group/$curriculumId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/my-subjects'
    | '/privacy-policy'
    | '/profile'
    | '/reviews'
    | '/sign-in'
    | '/sign-up'
    | '/term-of-use'
    | '/admin/curricula'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/programs'
    | '/my-subjects/grades'
    | '/my-subjects/plan'
    | '/my-subjects/progress'
    | '/my-subjects/transcript'
    | '/subjects/$subjectId'
    | '/admin/'
    | '/my-subjects/'
    | '/subjects/'
    | '/admin/curriculum-group/$curriculumId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MySubjectsRoute: typeof MySubjectsRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  ReviewsRoute: typeof ReviewsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermOfUseRoute: typeof TermOfUseRoute
  AdminCurriculaRoute: typeof AdminCurriculaRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminFacultiesRoute: typeof AdminFacultiesRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  AdminCurriculumGroupCurriculumIdRoute: typeof AdminCurriculumGroupCurriculumIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/term-of-use': {
      id: '/term-of-use'
      path: '/term-of-use'
      fullPath: '/term-of-use'
      preLoaderRoute: typeof TermOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-subjects': {
      id: '/my-subjects'
      path: '/my-subjects'
      fullPath: '/my-subjects'
      preLoaderRoute: typeof MySubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-subjects/': {
      id: '/my-subjects/'
      path: '/'
      fullPath: '/my-subjects/'
      preLoaderRoute: typeof MySubjectsIndexRouteImport
      parentRoute: typeof MySubjectsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-subjects/transcript': {
      id: '/my-subjects/transcript'
      path: '/transcript'
      fullPath: '/my-subjects/transcript'
      preLoaderRoute: typeof MySubjectsTranscriptRouteImport
      parentRoute: typeof MySubjectsRoute
    }
    '/my-subjects/progress': {
      id: '/my-subjects/progress'
      path: '/progress'
      fullPath: '/my-subjects/progress'
      preLoaderRoute: typeof MySubjectsProgressRouteImport
      parentRoute: typeof MySubjectsRoute
    }
    '/my-subjects/plan': {
      id: '/my-subjects/plan'
      path: '/plan'
      fullPath: '/my-subjects/plan'
      preLoaderRoute: typeof MySubjectsPlanRouteImport
      parentRoute: typeof MySubjectsRoute
    }
    '/my-subjects/grades': {
      id: '/my-subjects/grades'
      path: '/grades'
      fullPath: '/my-subjects/grades'
      preLoaderRoute: typeof MySubjectsGradesRouteImport
      parentRoute: typeof MySubjectsRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/admin/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculties': {
      id: '/admin/faculties'
      path: '/admin/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/curricula': {
      id: '/admin/curricula'
      path: '/admin/curricula'
      fullPath: '/admin/curricula'
      preLoaderRoute: typeof AdminCurriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/curriculum-group/$curriculumId': {
      id: '/admin/curriculum-group/$curriculumId'
      path: '/admin/curriculum-group/$curriculumId'
      fullPath: '/admin/curriculum-group/$curriculumId'
      preLoaderRoute: typeof AdminCurriculumGroupCurriculumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MySubjectsRouteChildren {
  MySubjectsGradesRoute: typeof MySubjectsGradesRoute
  MySubjectsPlanRoute: typeof MySubjectsPlanRoute
  MySubjectsProgressRoute: typeof MySubjectsProgressRoute
  MySubjectsTranscriptRoute: typeof MySubjectsTranscriptRoute
  MySubjectsIndexRoute: typeof MySubjectsIndexRoute
}

const MySubjectsRouteChildren: MySubjectsRouteChildren = {
  MySubjectsGradesRoute: MySubjectsGradesRoute,
  MySubjectsPlanRoute: MySubjectsPlanRoute,
  MySubjectsProgressRoute: MySubjectsProgressRoute,
  MySubjectsTranscriptRoute: MySubjectsTranscriptRoute,
  MySubjectsIndexRoute: MySubjectsIndexRoute,
}

const MySubjectsRouteWithChildren = MySubjectsRoute._addFileChildren(
  MySubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MySubjectsRoute: MySubjectsRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  ReviewsRoute: ReviewsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermOfUseRoute: TermOfUseRoute,
  AdminCurriculaRoute: AdminCurriculaRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminFacultiesRoute: AdminFacultiesRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  AdminCurriculumGroupCurriculumIdRoute: AdminCurriculumGroupCurriculumIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
