/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermOfUseRouteImport } from './routes/term-of-use'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MySubjectsRouteImport } from './routes/my-subjects'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects/$subjectId'
import { Route as AdminProgramsRouteImport } from './routes/admin/programs'
import { Route as AdminFacultiesRouteImport } from './routes/admin/faculties'
import { Route as AdminDepartmentsRouteImport } from './routes/admin/departments'
import { Route as AdminCurriculaRouteImport } from './routes/admin/curricula'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TermOfUseRoute = TermOfUseRouteImport.update({
  id: '/term-of-use',
  path: '/term-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MySubjectsRoute = MySubjectsRouteImport.update({
  id: '/my-subjects',
  path: '/my-subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/admin/programs',
  path: '/admin/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultiesRoute = AdminFacultiesRouteImport.update({
  id: '/admin/faculties',
  path: '/admin/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurriculaRoute = AdminCurriculaRouteImport.update({
  id: '/admin/curricula',
  path: '/admin/curricula',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-subjects': typeof MySubjectsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/term-of-use': typeof TermOfUseRoute
  '/admin/curricula': typeof AdminCurriculaRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-subjects': typeof MySubjectsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/term-of-use': typeof TermOfUseRoute
  '/admin/curricula': typeof AdminCurriculaRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/admin': typeof AdminIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-subjects': typeof MySubjectsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/term-of-use': typeof TermOfUseRoute
  '/admin/curricula': typeof AdminCurriculaRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/faculties': typeof AdminFacultiesRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/admin/': typeof AdminIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/my-subjects'
    | '/privacy-policy'
    | '/profile'
    | '/reviews'
    | '/sign-in'
    | '/sign-up'
    | '/term-of-use'
    | '/admin/curricula'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/programs'
    | '/subjects/$subjectId'
    | '/admin/'
    | '/subjects/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/my-subjects'
    | '/privacy-policy'
    | '/profile'
    | '/reviews'
    | '/sign-in'
    | '/sign-up'
    | '/term-of-use'
    | '/admin/curricula'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/programs'
    | '/subjects/$subjectId'
    | '/admin'
    | '/subjects'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/my-subjects'
    | '/privacy-policy'
    | '/profile'
    | '/reviews'
    | '/sign-in'
    | '/sign-up'
    | '/term-of-use'
    | '/admin/curricula'
    | '/admin/departments'
    | '/admin/faculties'
    | '/admin/programs'
    | '/subjects/$subjectId'
    | '/admin/'
    | '/subjects/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MySubjectsRoute: typeof MySubjectsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  ReviewsRoute: typeof ReviewsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermOfUseRoute: typeof TermOfUseRoute
  AdminCurriculaRoute: typeof AdminCurriculaRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminFacultiesRoute: typeof AdminFacultiesRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/term-of-use': {
      id: '/term-of-use'
      path: '/term-of-use'
      fullPath: '/term-of-use'
      preLoaderRoute: typeof TermOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-subjects': {
      id: '/my-subjects'
      path: '/my-subjects'
      fullPath: '/my-subjects'
      preLoaderRoute: typeof MySubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/admin/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculties': {
      id: '/admin/faculties'
      path: '/admin/faculties'
      fullPath: '/admin/faculties'
      preLoaderRoute: typeof AdminFacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/curricula': {
      id: '/admin/curricula'
      path: '/admin/curricula'
      fullPath: '/admin/curricula'
      preLoaderRoute: typeof AdminCurriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MySubjectsRoute: MySubjectsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  ReviewsRoute: ReviewsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermOfUseRoute: TermOfUseRoute,
  AdminCurriculaRoute: AdminCurriculaRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminFacultiesRoute: AdminFacultiesRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
